---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: specialty-components 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DineshGon/argocd.git
    targetRevision: HEAD
    path: environments/sit/progyny
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
     - Validate = true
     - CreateNamespace = false
     - PrunePropagationPolicy = foreground
     - PruneLast = true
